spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
